'use client';

import { useState, useEffect } from 'react';
import { Navbar } from '@/components/navbar';
import { Card, CardContent } from '@/components/ui/card';
import Image from 'next/image';
import { Loader2, Compass, Palette, Shirt } from 'lucide-react';
import { fetchTrendingOutfits, type FetchTrendingOutfitsOutput } from '@/ai/flows/fetch-trending-outfits-flow';
import { Separator } from '@/components/ui/separator';

export default function ExplorePage() {
  const [combinations, setCombinations] = useState<FetchTrendingOutfitsOutput['combinations']>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function getCombinations() {
      try {
        setIsLoading(true);
        const result = await fetchTrendingOutfits();
        setCombinations(result.combinations);
      } catch (error) {
        console.error("Failed to fetch trends:", error);
        // Handle error state if necessary
      } finally {
        setIsLoading(false);
      }
    }
    getCombinations();
  }, []);

  return (
    <div className="min-h-screen pb-20">
      <Navbar />
      <main className="container mx-auto px-4 pt-32">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-6 py-2 rounded-full glass text-primary text-xs font-bold uppercase tracking-widest mb-6 gold-glow">
            <Compass className="w-3 h-3 fill-current" />
            Style Sets
          </div>
          <h1 className="text-5xl md:text-7xl font-headline font-bold mb-4">Readymade Combinations</h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Get inspired with complete outfit sets and color palettes, generated by VYXEN AI.
          </p>
        </div>

        {isLoading ? (
          <div className="flex justify-center items-center h-64">
            <Loader2 className="w-16 h-16 animate-spin text-primary" />
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {combinations.map(combo => (
              <Card key={combo.id} className="glass border-white/5 overflow-hidden shadow-2xl hover:border-primary/40 transition-all group rounded-2xl flex flex-col">
                <div className="relative aspect-[4/5] overflow-hidden bg-muted">
                  <Image 
                    src={combo.imageUrl} 
                    alt={combo.name} 
                    fill 
                    className="object-cover group-hover:scale-105 transition-transform duration-700"
                    data-ai-hint={combo.imageHint}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" />
                  <div className="absolute bottom-0 left-0 p-6">
                    <h3 className="text-2xl font-bold font-headline text-white">{combo.name}</h3>
                  </div>
                </div>
                <CardContent className="p-6 flex flex-col flex-grow">
                  <p className="text-muted-foreground text-sm mb-6">{combo.description}</p>
                  
                  <div className="mb-6">
                    <h4 className="flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground tracking-widest mb-3">
                      <Palette className="w-4 h-4 text-primary" />
                      Color Palette
                    </h4>
                    <div className="flex gap-2">
                      {combo.colorPalette.map(color => (
                        <div key={color} className="w-6 h-6 rounded-full border-2 border-white/20" style={{ backgroundColor: color }} title={color} />
                      ))}
                    </div>
                  </div>

                  <Separator className="my-auto" />
                  
                  <div className="mt-6">
                    <h4 className="flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground tracking-widest mb-4">
                      <Shirt className="w-4 h-4 text-primary" />
                      Outfit Items
                    </h4>
                    <ul className="space-y-2">
                      {combo.items.map(item => (
                        <li key={item.name} className="flex items-center gap-3 text-sm">
                          <span className="font-semibold text-primary/80 w-20 shrink-0">{item.type}</span>
                          <span className="text-white">{item.name}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
